### ISSUE TITLE
anyOf() throws ClassCastException when used with pattern match.

### ISSUE THREAD

**Issue by FuncGuy** [vavr-io/vavr#2419] opened 2019-06-16 02:34 UTC
Hi,

@danieldietrich i'm getting the below exception when i match against using  anyOf predicate i'm not sure whether this is the actual behaviour or it needs a fix. Thanks..

java.lang.ClassCastException: class io.vavr.collection.List$Cons cannot be cast to class java.lang.Number (io.vavr.collection.List$Cons is in unnamed module of loader 'app'; java.lang.Number is in module java.base of loader 'bootstrap')

    public void shouldPatternMatchForGivenPredicate() {

         List<Integer> list = List(1, 2, 3);
         Predicate<Number> p = n -> n.intValue() > 0;
         Match(list).of(
                Case($(anyOf(p)), true),
                Case($(), false)
        );

    }

**Comment by danieldietrich** [comment] 2019-07-04 20:33
Thx! Interesting - this should not happen. In fact there should be a compile error if you do it this way because the List is matched, not the contained elements. Will check that!

**Comment by danieldietrich** [comment] 2019-07-04 21:43
I will close this because it can't be reproduced. Maybe you used an outdated version of VAVR?

I implemented the test case you provided. The CI build passed for jdk8, jdk9, jdk10, jdk11 and jdk12.

PR: https://github.com/vavr-io/vavr/pull/2428

CI: https://travis-ci.org/vavr-io/vavr/builds/554424019

**Comment by danieldietrich** [comment] 2019-07-17 13:14
Now it hit me in #2452.

**Comment by danieldietrich** [comment] 2019-07-19 01:11
It isn't a VAVR bug. It is a wrong application of pattern matching.

This is the way it works:

```diff
public void shouldPatternMatchForGivenPredicate() {

     List<Integer> list = List(1, 2, 3);
     Predicate<Number> p = n -> n.intValue() > 0;
     Match(list).of(
            Case($(l -> l.exists(anyOf(p))), true),
            Case($(), false)
    );

}
```

**Closed by danieldietrich** 2019-07-19 01:11 UTC
Labels: question
