### ISSUE TITLE
Site docs.vavr.io fora do ar.

### ISSUE THREAD

**Issue by CassioGangrel** [vavr-io/vavr#2762] opened 2024-04-26 13:19 UTC
Hello! The site of the documentation is offline: http://docs.vavr.io/

**Comment by kazimir-lyshchynski** [comment] 2024-04-27 21:47
Last commit was dated at last year. Maybe the project can be represented as dead.

**Comment by outsideMyBox** [comment] 2024-04-29 11:32
Just for info, until it is available again, the doc can be found here: https://github.com/vavr-io/vavr-docs/blob/gh-pages/index.html

**Comment by forresthopkinsa** [comment] 2024-04-29 17:05
Duplicate of #2756

**Closed** 2024-05-03 14:22 UTC
