### ISSUE TITLE
Method "asJava" for Map and Set

### ISSUE THREAD

**Issue by mincong-h** [vavr-io/vavr#2607] opened 2020-07-18 19:29 UTC
In `Seq` interface, there is an `asJava()` method which creates an immutable `java.util.List` view on top of the `Seq`. It will be cool to see the same method for all the implementations of `Set` and `Map`, because it's a convenient way to go back from Vavr to Java collection. Compared to existing methods  `toJava{Type}`, this syntax is shorter, and the type information is provided implicitly by the current object itself, i.e. Set -> Java Set, Map -> Java Map, etc. We can also provide similar methods, e.g. `asJavaMutable`, with and without the consumer as input parameter. I can prepare a PR if you think it's a good idea.

**Comment by danieldietrich** [comment] 2020-07-28 22:49
Hi Mincong,
this is a duplicate of #1933, hence I will close this.
A work on this issue is very welcome!

I put much effort in testing the view methods and compared our List view with Java's ArrayList etc. I think.
Our views need to exactly behave like the Java collections, which wasn't trivial. Please take a look at the comments and existing tests...

Thanks! :)

**Closed by danieldietrich** 2020-07-28 22:49 UTC
